## Pytorch ( facebook)

### 1) Tensor
* 다차원 배열

In [2]:
import numpy as np
import torch

# 학습시킬때는 tensor로 사용 ( cpu, gpu 사용 )
# predict할때는 다시 numpy 

li = np.array([[1, 2], [3, 4]])

#넘파이배열을 텐서로 변환

tensor1 = torch.tensor(li)

tensor2 = torch.as_tensor(li)

tensor3 = torch.from_numpy(li)

print(tensor1)

print(tensor2)

print(tensor3)


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [3]:
##############################

#텐서를 넘파이배열로 변환

print(tensor1.numpy())

print(tensor2.numpy())

print(tensor3.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
##############################
# torch 난수 생성

torch.manual_seed(0) #랜덤시드 고정

a = torch.rand(5) # 0 ~ 1 사이의 5개의 난수

b = torch.randn(5) # 평균 0, 표준편차 1인 5개의 난수

c = torch.randint(10, size=(5,)) # 0~9 사이의 5개의 난수

print(a)

print(b)

print(c)


tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([ 0.5507,  0.2704,  0.6472,  0.2490, -0.3354])
tensor([8, 4, 3, 6, 9])


In [5]:
##############################

print(torch.arange(1, 10)) # 1~9

print(torch.ones((2, 5))) # 2행 5열, 1로 채움

print(torch.zeros((3, 5))) #3행 5열, 0으로 채움

print(torch.linspace(0, 10, 5)) # 0~10, 5등분

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [6]:
##############################

#텐서의 형상 변환(reshape)

t1 = torch.ones(4, 3)

t2 = t1.view(3, 4) #3행 4열로 변환

t3 = t1.view(12) #1차원 배열로 변환

print(t1)

print(t2)

print(t3)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [7]:
##############################

t1.view(1, 3, 4) #3차원으로 변환

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### 2) iris 데이터셋

In [8]:
from sklearn.datasets import load_iris

# iris 데이터셋 로딩

X, y = load_iris(return_X_y=True)

print(X[:5])

print(y[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [28]:
##############################

from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split( X, y, random_state=10, test_size=0.2, stratify=y, shuffle=True )

print(len(X_train))    
print(type(X_train))
print(X_train.shape)


120
<class 'numpy.ndarray'>
(120, 4)


In [13]:
##############################

from torch import nn

import torch.nn.functional as F

#신경망 모형

class Model(nn.Module):

    def __init__(self, input_dim):

        super(Model, self).__init__()

        #input layer, Linear 선형함수(1차함수)

        #input nodes, output nodes 50

        self.layer1 = nn.Linear(input_dim,50) 

        self.layer2 = nn.Linear(50, 20)

        self.layer3 = nn.Linear(20, 3)

        

    def forward(self, x):

        x = F.relu(self.layer1(x))

        x = F.relu(self.layer2(x))

        # 출력층의 활성화함수 - 소프트맥스

        x = F.softmax(self.layer3(x), dim=0)

        return x

In [14]:
##############################

import torch

model = Model(X_train.shape[1]) # 초기화함수의 input_dim으로 변수개수가 전달됨

optimizer = torch.optim.Adam(model.parameters(), lr=0.01) # 최적화함수 정의

loss_fn = nn.CrossEntropyLoss() #손실함수 정의

epochs = 100

In [18]:
##############################

from torch.autograd import Variable

#넘파이배열로부터 텐서를 만들고
X_train = Variable(torch.from_numpy(np.array(X_train))).float()  # 메모리 => cpu,gpu
y_train = Variable(torch.from_numpy(np.array(y_train))).long()
#label = Variable(torch.from_numpy(np.array(label)).float()).to(device)

for epoch in range(1, epochs+1):

    print("Epoch",epoch)

    #예측값

    y_pred = model(X_train)

    #손실함수에 예측값과 실제값을 입력

    loss = loss_fn(y_pred, y_train)

    print('loss:',loss.item())

    

    # 경사 초기화

    optimizer.zero_grad()

    loss.backward() # 역전파

    optimizer.step() # 가중치 업데이트

Epoch 1
loss: 1.098368763923645
Epoch 2
loss: 1.09757661819458
Epoch 3
loss: 1.0969760417938232
Epoch 4
loss: 1.0962201356887817
Epoch 5
loss: 1.0953227281570435
Epoch 6
loss: 1.0942963361740112
Epoch 7
loss: 1.093174695968628
Epoch 8
loss: 1.0920960903167725
Epoch 9
loss: 1.0910488367080688
Epoch 10
loss: 1.0901483297348022
Epoch 11
loss: 1.0894235372543335
Epoch 12
loss: 1.088867425918579
Epoch 13
loss: 1.0883787870407104
Epoch 14
loss: 1.087942123413086
Epoch 15
loss: 1.0875487327575684
Epoch 16
loss: 1.0872578620910645
Epoch 17
loss: 1.0870704650878906
Epoch 18
loss: 1.0868990421295166
Epoch 19
loss: 1.0867153406143188
Epoch 20
loss: 1.0865654945373535
Epoch 21
loss: 1.086439847946167
Epoch 22
loss: 1.0863085985183716
Epoch 23
loss: 1.086158275604248
Epoch 24
loss: 1.0859640836715698
Epoch 25
loss: 1.0857325792312622
Epoch 26
loss: 1.0855315923690796
Epoch 27
loss: 1.085354208946228
Epoch 28
loss: 1.0851529836654663
Epoch 29
loss: 1.084934115409851
Epoch 30
loss: 1.0846964120864868

In [19]:
##############################

# Prediction

X_test = Variable(torch.from_numpy(X_test)).float()

pred = model(X_test)

pred[:5]


tensor([[1.4967e-07, 4.3045e-03, 8.2617e-05],
        [3.3400e-02, 2.4500e-07, 6.6396e-12],
        [7.2018e-08, 1.2540e-03, 2.1329e-04],
        [2.8003e-08, 7.0835e-04, 6.0539e-04],
        [6.8303e-06, 3.0979e-01, 9.3650e-07]], grad_fn=<SliceBackward0>)

In [21]:
##############################

import numpy as np

np.argmax(pred.data.numpy(), axis=1)

array([1, 0, 1, 1, 1, 2, 0, 2, 2, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 2,
       2, 0, 0, 1, 1, 0, 1, 1], dtype=int64)

In [22]:
##############################

from sklearn.metrics import accuracy_score

# 모형의 정확도 측정

accuracy_score(y_test, np.argmax(pred.data.numpy(), axis=1))

0.9666666666666667

In [23]:
##############################

torch.save(model, "../MODL/iris-torch.h5")

In [31]:
##############################

model2 = torch.load("../MODL/iris-torch.h5")


#np.argmax(model2(X_test[0]).data.numpy())

#X_test = Variable(torch.from_numpy(X_test)).float()
np.argmax(model2(Variable(torch.from_numpy(X_test[0])).float()).data.numpy())

2

In [ ]:
!pip install torchinfo

In [27]:
##############################

#pip install torchinfo

from torchinfo import summary

summary(model)

# input_size=(batch size, input nodes)

summary(model, input_size=(32, 4)) # 미니배치

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [32, 3]                   --
├─Linear: 1-1                            [32, 50]                  250
├─Linear: 1-2                            [32, 20]                  1,020
├─Linear: 1-3                            [32, 3]                   63
Total params: 1,333
Trainable params: 1,333
Non-trainable params: 0
Total mult-adds (M): 0.04
Input size (MB): 0.00
Forward/backward pass size (MB): 0.02
Params size (MB): 0.01
Estimated Total Size (MB): 0.02